FROM node:lts-alpine
ARG NPM_TOKEN
ENV NPM_TOKEN=${NPM_TOKEN}
ENV PORT 3000

WORKDIR /usr/src/app

# Installing dependencies
COPY package.json yarn.lock .npmrc ./
RUN npm config set '//npm.fontawesome.com/:_authToken' "${NPM_TOKEN}"
RUN yarn install

# Running the app
EXPOSE 3000
CMD ["yarn", "dev"]
